class PlaceInfo {
  final String location,image,title,offre,Hotels,desc;
  final double prix,starts;
  final List photos;
  PlaceInfo({
    required this.Hotels,
    required this.location,
    required this.desc,
    required this.starts,
    required this.offre,
    required this.prix,
    required this.image,
    required this.title,
    required this.photos,
 
    });
  
}

 final List<PlaceInfo> places = [
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Sousse", 
   desc: "cated in Sousse, less than 1 km from Las Vegas Beach, Occidental Sousse Marhaba provides accommodation with an outdoor swimming pool, free private parking, a garden and a terrace.", 
   starts:4.5,
    offre: "/All Inclusive Soft Drink",
    prix: 349.333,
    image: "assets/tours/tun1.jpg",
    title: "Occidental Sousse Marhaba...",
    photos: ['assets/photos/a1.jpeg','assets/photos/a2.jpeg','assets/photos/a3.jpeg','assets/photos/a4.jpeg'],
       
  ),

  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Mounastir", 
   desc: "Located in the tourist area of ​​Monastir, between Sousse and Monastir on a fine sandy Mediterranean beach, and opposite the 18-hole Palm Links Golf course", 
   starts: 5,
    offre: "/All Inclusive Soft Drink",
     prix: 210.167,
      image: "assets/tours/tun2.jpg",
       title: "Houda Golf Beach",
       photos: ['assets/photos/b1.jpeg','assets/photos/b2.jpeg','assets/photos/b3.jpeg','assets/photos/b4.jpeg'],
  ),

  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Hammamet", 
   desc: "The hotel has 2 large pools, 1 main terrace, 1 aqua park and a splash pool with slides from 01/05 with plenty of room for all guests. Our restaurant service ...", 
   starts: 4.5,
    offre: "/All Inclusive Soft Drink",
     prix: 269.833,
      image: "assets/tours/tun3.jpg",
       title: "Omar Khayam",
      photos:['assets/photos/c1.jpeg','assets/photos/c2.jpeg','assets/photos/c3.jpeg','assets/photos/c4.jpeg'],
  ),

  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Hammamet", 
   desc: "Book Hotel Club President, Hammamet. No Booking Fees. Flight + Hotel. Authentic Reviews. Hotels. Villas. Wide Choice. We Speak Your Language. Motels.", 
   starts: 4.5,
    offre: "/Logement Petit Déjeuner",
     prix: 203.333,
      image: "assets/tours/tun4.jpg",
       title: "Golden Tulip President",
       photos:['assets/photos/d1.jpeg','assets/photos/d2.jpeg','assets/photos/d3.jpeg'],
  ),

  PlaceInfo(
    Hotels: "Top Hôtels 2024",
   location: "Hammamet", 
   desc: "Located on the shores of the Mediterranean, the Dar Khayam hotel is a charming establishment offering an idyllic setting for family holidays..", 
   starts: 4,                                                                       
    offre: "/All Inclusive Soft Drink",
     prix: 269.833,
      image: "assets/tours/tun5.jpg",
       title: "Dar Khayam",
       photos: ['assets/photos/e1.jpeg','assets/photos/e2.jpeg','assets/photos/e3.jpeg'],
  ),

  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Djerba", 
   desc: "Iberostar Waves Mehari Djerba · Beachfront · Surrounded by extensive gardens · Wooden bungalows · Aquafun pool · Beach bar offering Mediterranean cuisine ...", 
   starts: 5.5,
    offre: "/Logement Seul",
     prix: 416.5,
      image: "assets/tours/tun6.jpg",
       title: "Iberostar Mehari",
       photos: ['assets/photos/f1.jpeg','assets/photos/f2.jpeg','assets/photos/f3.jpeg'],
  ),
  PlaceInfo(
    Hotels: "Top Hôtels 2024",
   location: "Sousse", 
   desc: "With its 222 newly renovated rooms and suites, superbly designed and offering breathtaking views of the city or the sea, the Sousse Pearl Marriott Resort & Spa is the place that redefines trends.", 
   starts: 4.5,
    offre: "/Logement Petit Déjeuner",
     prix: 286,
      image: "assets/tours/tun7.jpg",
       title: "Pearl Marriott Resort",
       photos: ['assets/photos/j1.jpeg','assets/photos/j2.jpeg','assets/photos/j3.jpeg'],
  ),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Mahdia", 
   desc: "Mahdia Beach & Aqua Park is a four-star hotel, located in Mahdia, Tunisia, less than 40 km from Monastir International Airport..", 
   starts: 4,
    offre: "/All Inclusive Soft Drink",
     prix:358.167,
      image: "assets/tours/tun8.jpg",
       title: "Mahdia Beach",
       photos: ['assets/photos/k1.jpeg','assets/photos/k2.jpeg','assets/photos/k3.jpeg'],
  ),
 PlaceInfo(
     Hotels: "Top Hôtels 2024",
     location: "Mounastir", 
     desc: "Welcome to One Resort Aqua Park & ​​Spa, your home away from home in Monastir. One Resort Aqua Park & ​​Spa strives to make your stay as enjoyable and relaxing as possible", 
     starts: 4.5,
     offre: "/All Inclusive Soft Drink",
     prix:300.5,
     image: "assets/tours/tun9.jpg",
     title: "Resort Aqua Park",
     photos:['assets/photos/l1.jpeg','assets/photos/l2.jpeg','assets/photos/l3.jpeg'],
 ),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
    location: "Mounastir", 
    desc: "One Resort Monastir is located directly at the beach, just a few minutes from Monastir airport (approx. 2 km), 3 km from Flamingo golf course, approximately 8 km from the center of Monastir", 
    starts: 4.7,
    offre: "/All Inclusive Soft Drink",
    prix: 320.5,
    image: "assets/tours/tun10.jpg",
    title: "One Resort Jokey",
    photos: ['assets/photos/m1.jpeg','assets/photos/m2.jpeg','assets/photos/m3.jpeg'],
    ),
  PlaceInfo(
   Hotels: "Top Hôtels 2024",
   location: "Mahdia", 
   desc: "Welcome to PrimaSol El Mehdi, your home away from home in Mahdia. PrimaSol El Mehdi does everything to make your stay as enjoyable and relaxing as possible. That's why so many guests return year after year.", 
   starts: 4.5,
   offre: "/All Inclusive Soft Drink",
   prix: 213.667,
   image: "assets/tours/tun11.jpg",
   title: "El Mehdi Beach",
   photos:['assets/photos/n1.jpeg','assets/photos/n2.jpeg','assets/photos/n3.jpeg'],
   ),
 PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Sousse", 
   desc: "Marhaba Club is fully dedicated to anticipating your needs and meeting your expectations. Located in the heart of the tourist area of ​​the city of Sousse.", 
   starts: 4.8,
    offre: "/All Inclusive Soft Drink",
     prix:326,
      image: "assets/tours/tun12.jpg",
       title: "Marhaba Club",
       photos: ['assets/photos/o1.jpeg','assets/photos/o2.jpeg','assets/photos/o3.jpeg'],
       ),
  PlaceInfo(
    Hotels: "Top Hôtels 2024",
   location: "Hammamet", 
   desc: "For a stay in Hammamet, the Hawaï Beach Club hotel is a must in terms of accommodation. Decorated by palm gardens and the fine sand of the beach, it is a place of well-being, a paradise corner.", 
   starts: 5,
    offre: "/All Inclusive Soft Drink",
     prix: 171.167,
      image: "assets/tours/tun13.jpg",
       title: "Hotel Tanfous (Hawaï Beach)",
       photos: ['assets/photos/p1.jpeg','assets/photos/p2.jpeg','assets/photos/p3.jpeg'],
       ),
       
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Djerba", 
   desc: "The Vincci Helios Beach 4* hotel, located in Djerba, is a heavenly destination in the heart of Tunisia. On the seaside, on a breathtaking beach on the island of Djerba, where the Mediterranean merges with the Sahara", 
   starts: 5.3,
    offre: "/All Inclusive Soft Drink",
     prix: 384.333,
      image: "assets/tours/tun14.jpg",
       title: "Vincci Helios Beach",
       photos: ['assets/photos/q1.jpeg','assets/photos/q2.jpeg','assets/photos/q3.jpeg'],),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Mounastir", 
   desc: "Shems Holiday Village is an all-inclusive beachfront holiday village set in 24 hectares of gardens", 
   starts: 4.5,
    offre: "/Logement Petit Déjeuner",
     prix: 211.667,
      image: "assets/tours/tun15.jpg",
       title: "Shems Holiday Village & Aquapark",
       photos: ['assets/photos/r1.jpeg','assets/photos/r2.jpeg','assets/photos/r3.jpeg'],),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Mahdia", 
   desc: "Equipped with air conditioning and a minibar, rooms at Club Thapsus Hotel offer all the comfort you need. You can even stay connected with internet access.", 
   starts: 4.9,
    offre: "/Demi Pension Plus",
     prix: 151.333,
      image: "assets/tours/tun16.jpg",
       title: "Thapsus Beach Resort",
       photos: ['assets/photos/s1.jpeg','assets/photos/s2.jpeg','assets/photos/s3.jpeg'],),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Sousse", 
   desc: "Located in the greenery of the high-end hotel, set in the greenery on the seafront 4 km from the city of Sousse and 3 km from Port El Kantaoui and the golf course (36 holes) 30 minutes from Enfidha airport", 
   starts: 4.5,
    offre: "/Logement Petit Déjeuner",
     prix: 129.333,
      image: "assets/tours/tun17.jpg",
       title: "Royal Jinene",
       photos: ['assets/photos/t1.jpeg','assets/photos/t2.jpeg','assets/photos/t3.jpeg'],),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Sousse", 
   desc: "Freshly renovated, this sublime 4-star hotel located in one of the best sites in Sousse will give you an unforgettable experience, whether inside or outside, everything is done to make you feel comfortable.", 
   starts: 4.5,
    offre: "/Demi Pension",
     prix: 134,
      image: "assets/tours/tun18.jpg",
       title: "Golf Residence",
       photos: ['assets/photos/u1.jpeg','assets/photos/u2.jpeg','assets/photos/u3.jpeg'],),
  PlaceInfo(
    Hotels: "Tarifs imbattables Active Travel",
   location: "Sousse", 
   desc: "Les Orangers Beach Resort & Bungalows is a 4-star luxury establishment. Stays at Les Orangers hotel are of infinite comfort and unlimited luxury.", 
   starts: 5,
    offre: "/All Inclusive Soft Drink",
     prix:490.167,
      image: "assets/tours/tun19.jpg",
       title: "Les Orangers Beach",
       photos: ['assets/photos/v1.jpeg','assets/photos/v2.jpeg','assets/photos/v3.jpeg'],),
  PlaceInfo(
    Hotels: "Promo -20%",
   location: "Mounastir", 
   desc: "Hotel Delphin El Habib is a 4-star hotel located on the seafront in the city center of Monastir, offers several services..", 
   starts: 5.2,
    offre: "/Logement Petit Déjeuner",
     prix: 186.333,
      image: "assets/tours/tun20.jpg",
       title: "Delphin Hotels,Resorts",
       photos: ['assets/photos/w1.jpeg','assets/photos/w2.jpeg','assets/photos/w3.jpeg'],),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Mounastir", 
   desc: "The Rosa Beach Hotel is located in the heart of the Skanès hotel resort, on a fine sandy Mediterranean beach, 7km from the center of Monastir.", 
   starts: 3.9,
    offre: "/All Inclusive Soft Drink",
     prix: 131,
      image: "assets/tours/tun21.jpg",
       title: "Rosa Beach Thalasso",
       photos: ['assets/photos/x1.jpeg','assets/photos/x2.jpeg','assets/photos/x3.jpeg'],),
  PlaceInfo(
    Hotels: "Top Hôtels 2024",
   location: "Mounastir", 
   desc: "Located halfway between Sousse and Monastir, the Palmyra Holiday Resort welcomes you a stone's throw from the beach on the Tunisian coast, in the tourist district of Skanes.", 
   starts: 4.5,
    offre: "/All Inclusive Soft Drink",
     prix: 170.5,
      image: "assets/tours/tun22.jpg",
       title: "Chiraz Club",
       photos:['assets/photos/y1.jpeg','assets/photos/y2.jpeg','assets/photos/y3.jpeg'],),
  PlaceInfo(
    Hotels: "Top Hôtels 2024",
   location: "Sousse", 
   desc: "Discover the Houria Palace Sousse hotel: Houria Palace, known above all for its warm atmosphere, is a 4-star hotel establishment,", 
   starts: 5.9,
    offre: "/All Inclusive Soft Drink",
     prix: 81.333,
      image: "assets/tours/tun23.jpg",
       title: "Houria Palace",
       photos: ['assets/photos/z1.jpeg','assets/photos/z2.jpeg','assets/photos/z3.jpeg'],),
  PlaceInfo(
    Hotels: "Hôtels avec Toboggan",
   location: "Hammamet", 
   desc: "Discover the Hotel Nozha Beach Resort & Spa Hammamet. Nozha Beach Resort & Spa is a waterfront hotel, special for families, it is the best ...", 
   starts: 4.5,
    offre: "/Soft All Inclusive",
     prix: 399.833,
      image: "assets/tours/tun24.jpg",
       title: "Nozha Beach Resort",
       photos: ['assets/photos/z4.jpeg','assets/photos/z5.jpeg','assets/photos/z6.jpeg'],),
];
